### ISSUE TITLE
Create Toil appliance

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/toil#1088]
Create a Docker image with Mesos and Toil in it. Ultimately we'll also need Docker inside the image but we'll ignore that fact for now. There also needs to be a wrapper.sh or wrapper.py that is set as the ENTRYPOINT of the image. That wrapper needs to determine if the container is invoked as a leader or worker and start mesos-master or mesos-slave accordingly. 

Let's brainstorm this a bit on Monday, @cket.

TODO:
- [ ] Merge https://github.com/BD2KGenomics/cgl-docker-lib/pull/160
- [ ] Resolve https://github.com/BD2KGenomics/cgl-docker-lib/issues/162
- [ ] Merge #1088

**Comment by hannes-ucsc** [comment]
Use the Mesos dockerimage as a base.

**Comment by fnothaft** [comment]
Mesos publishes two images:

* https://hub.docker.com/r/mesosphere/mesos-master/
* https://hub.docker.com/r/mesosphere/mesos-slave/

**Comment by fnothaft** [comment]
I'll draft this up by EOD tomorrow; @cket can you help to test this out? Let's sync up after the pipelines-scrum tomorrow.

**Comment by cket** [comment]
Definitely, talk to you then!

**Comment by fnothaft** [comment]
TODO:
- [ ] Merge https://github.com/BD2KGenomics/cgl-docker-lib/pull/160
- [ ] Resolve https://github.com/BD2KGenomics/cgl-docker-lib/issues/162

**Comment by hannes-ucsc** [comment]
@fnothaft, I copied your two TODO's to the description and added a third one.
