### ISSUE TITLE
Toil Roadmap

### ISSUE THREAD

**Issue by ejacox** [BD2KGenomics/toil#1922]
This issues captures the goals of the Toil workflow engine project. These are divided into three categories based on when they will be addressed. Given that the project advances thanks to a team of mostly students and external collaborators, these are only rough estimates.

Feedback is welcome. Every effort will be made to put resources on any critical goals.

# Near Term (In Progress)
- Ansible provisioning.
   - [ ] Azure
   - [ ] AWS
- [ ] Google provisioning
- [ ] Fix flaky tests
- [ ] Run massive workflows
- [ ] Better feedback (error messages, logging).

# Medium Term (~ 6-month goals)
* Batch systems
   - [ ] Google Pipelines
   - [ ] Azure Batch
   - [ ] AWS Batch
- [ ] Containerize leader (work with Consonance)
* Improve the user experience.
   - [ ] Change the thread pool model to improve single machine usage.
* Improve the development process.
   - [ ] Add a linter
   - [ ] Add a code coverage tool.
   - [ ] Organize tests.
   - [ ] Better access to tests for external developers.
- [ ] TES support
- [ ] WES Support

# Longer Term
- [ ] Better track versions of specifications (e.g. CWL, WDL) and dependencies.
- [ ] Add other provisioners: OpenStack
- [ ] Singularity support.
- [ ] Uniform configuration (i.e. not just environment variables).
- [ ] Add management and monitoring UIs.
- [ ] Python 3 support.
- [ ] Add URL wrapping for streaming instead of copying.

# Completed
- [x] Basic WDL support.
- [x] Travis CI for commits.
 - [x] Run Toil within Popper (https://cross.ucsc.edu/tag/popper/).
 - [x] Grafana for workflow monitoring
- [x]  Update the Azure jobStore.
 - [x] Finish Google jobStore (GCP)
