### ISSUE TITLE
GCE Provisioner TODO

### ISSUE THREAD

**Issue by ejacox** [BD2KGenomics/toil#2096]
- [ ]  - libcloud ex_create_multiple_nodes bug that doesn't allow multi nodes
     - submit issue?
     - Or just keep class with machine name as uuid?
- [ ] copy SSE keys for server side encryption
- [ ] rename to Google (instead of GCE?)
